# Generated by Django 3.2.3 on 2021-07-03 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_payments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payments',
            old_name='email',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='payments',
            name='amount',
        ),
        migrations.AddField(
            model_name='payments',
            name='amo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.order'),
        ),
    ]
